#!/bin/sh

set -eu

# Dependencies
#
# ```zsh
# # e.g. on Gentoo Linux
# % sudo emerge -av \
#   dev-libs/elfutils \
#   dev-util/cmake \
#   sys-devel/make \
#   net-misc/curl \
#   app-arch/tar
# ```
#

work_dir="$(dirname $(readlink -f "${0}"))/kcov"

# if set KCOV_DISCARD_CACHE=true, then kcov will be force-installed
force_install="${KCOV_DISCARD_CACHE:-false}"

kcov_pfx="${KCOV_PREFIX:-"${work_dir}"}"
kcov_cmd="${kcov_pfx}/bin/kcov"
kcov_url="https://github.com/SimonKagstrom/kcov/archive"
kcov_ver="v38"

if [[ -f "${kcov_cmd}" && "${force_install}" != "true" ]]; then
  echo "kcov already installed at ${kcov_cmd}"
else
  rm -fr $work_dir
  mkdir $work_dir
  cd $work_dir

  curl -sLO ${kcov_url}/${kcov_ver}.tar.gz
  mkdir $kcov_ver
  tar zxvf ${kcov_ver}.tar.gz -C $kcov_ver --strip-components=1

  cd $kcov_ver
  mkdir build
  cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=$kcov_pfx
  make
  make install
fi
